#overused words in AI-generated writing (stored in a set as required)
ai_overused_words = {
    "however", "moreover", "therefore", "furthermore",
    "significant", "numerous", "crucial", "advancements",
    "potential", "impact", "beneficial", "complex",
    "various", "important", "challenges"
}


def main():
    """
    Main function to orchestrate the program flow and tell the story of the program.
    """
    #program description function
    displayProgramDescription()

    #input
    passage = getTextInput()

    #processing
    found_overused = passageContainsOverusedWords(passage)

    #output
    displayResult(found_overused)


def displayProgramDescription():
    """
    Displays a brief description of the program's purpose.
    """
    print("This program will check a user-supplied passage for commonly overused words\n"+
          "in AI-generated writing. If an overused word is found, it may indicate\n"+
          "that the passage was generated by AI.\n")


def getTextInput():
    """
    Prompts the user to enter a passage of any length to be checked.

    Parameters:
        none

    Returns:
        str: The passage the user has input.
    """
    #get user input string
    passage_input = input("Enter a passage of any length to check for commonly overused words in AI-generated writing: ")
    return passage_input #return the passage string


def passageContainsOverusedWords(passage):
    """
    Checks whether the passage contains any of the overused words (stored in a set). Matching is case-insensitive.

    Parameters:
        passage (str): The passage to check.

    Returns:
        bool: True if any overused word was found, False if it doesn't.
    """
    passage_lower = passage.lower()
    for word in ai_overused_words:
        if word in passage_lower:
            return True #an overused word was found
    return False #no overused words were found


def displayResult(found_overused):
    """
    Displays the result: suspect AI if an overused word was found; otherwise human-written.

    Parameters:
        found_overused (bool): True if an overused word was found in the passage.
    """
    if found_overused: #if an overused word was found display the following...
        print("There is reason to suspect the passage was generated by AI.")
    else: #if no overused words were found display the following...
        print("The passage appears to be written by a human.")


#call main function when script is executed
if __name__ == "__main__":
    main()
